import math
import imageio.v2 as imageio


def make_lut(src, size=33):
    res = math.ceil(math.sqrt(size ** 3) / size) * size

    img = imageio.imread(src)
    img = img.astype(dtype='float64')
    img /= float(2 ** 16 - 1)

    counter = 0

    output = "TITLE \"Generated by Jan Lohse\"\nLUT_3D_SIZE " + str(size) + "\n"

    for r in range(size):
        for g in range(size):
            for b in range(size):
                output += "\n{:.7f} {:.7f} {:.7f}".format(*img[counter // res, counter % res])
                counter += 1

    f = open(src.split('.')[0] + '.cube', 'w')
    f.write(output)
    f.close()


make_lut('FilmboxCustom.tif', size=65)